### ISSUE TITLE
Build dockerize plugin to run on SBH

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/Plugin-Submit-Excel-Composition#4]
As noted in @IsabelMarleen 's [GSoC presentation](https://medium.com/@IsaMarleen/additional-resource-832b6067afec), one goal for the project is to create a dockerize plugin that can be installed and run on a SBH instance. This has not yet been implemented and this issue documents this feature request.

**Comment by JMante1** [comment]
This has now been successfully done
