### ISSUE TITLE
Include pandas and numpy to requirements.txt

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/Plugin-Submit-Excel-Composition#5]
Project will not compile successfully for [Composition_reading.py](https://github.com/SynBioHub/Plugin-Submit-Excel-Composition/blob/master/Composition_reading.py) if a user does not have pandas and numpy installed.  Please, update [requirements.txt](https://github.com/SynBioHub/Plugin-Submit-Excel-Composition/blob/master/requirements.txt) to include these two packages.

**Comment by IsabelMarleen** [comment]
I updated the requirements.txt file to include pandas and numpy. Thank you for pointing it out
